#!/bin/bash
# This file was created automatically by cotor as a tool wrapper.

DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

composer install --working-dir=$DIR/.behat --quiet
exec $DIR/.behat/vendor/bin/behat "$@"
